-- ============================================================
-- SMARTFUEL OS — DISABLE ALL RLS POLICIES FOR CLIENT REVIEW
-- Run this in your Supabase SQL Editor if you get RLS policy errors!
-- ============================================================

ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE shifts DISABLE ROW LEVEL SECURITY;
ALTER TABLE nozzles DISABLE ROW LEVEL SECURITY;
ALTER TABLE fuel_stock DISABLE ROW LEVEL SECURITY;
ALTER TABLE fuel_readings DISABLE ROW LEVEL SECURITY;
ALTER TABLE branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_closing DISABLE ROW LEVEL SECURITY;
ALTER TABLE fuel_refills DISABLE ROW LEVEL SECURITY;
ALTER TABLE fuel_activity_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_insights DISABLE ROW LEVEL SECURITY;
ALTER TABLE fraud_alerts DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_predictions DISABLE ROW LEVEL SECURITY;
ALTER TABLE alert_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE automation_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE leave_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE salaries DISABLE ROW LEVEL SECURITY;
